name: Code Scan and Remediation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Clear pip cache to avoid any cached dependencies
      - name: Clear pip cache
        run: |
          python -m pip cache purge

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Code Scan on Modified Files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py


      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v2
        with:
          name: Vulnerability Report
          path: vulnerability_report.md