name: Code Scan and Remediation

# Triggers the workflow on pushes and pull requests
on:
  push:
    branches:
      - '*'          # Run on pushes to all branches
  pull_request:
    branches:
      - '*'          # Run on all pull requests

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last two commits to enable git diff for modified files

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the code scan on modified files
      - name: Run Code Scan on Modified Files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py
